# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(356, 149)
        MainWindow.setMaximumSize(QtCore.QSize(356, 149))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_key_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_key_pushButton.setObjectName("load_key_pushButton")
        self.horizontalLayout.addWidget(self.load_key_pushButton)
        self.key_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.key_lineEdit.setEnabled(True)
        self.key_lineEdit.setReadOnly(True)
        self.key_lineEdit.setObjectName("key_lineEdit")
        self.horizontalLayout.addWidget(self.key_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_file_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_file_pushButton.setObjectName("load_file_pushButton")
        self.horizontalLayout_2.addWidget(self.load_file_pushButton)
        self.file_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_lineEdit.setEnabled(True)
        self.file_lineEdit.setReadOnly(True)
        self.file_lineEdit.setObjectName("file_lineEdit")
        self.horizontalLayout_2.addWidget(self.file_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.generate_key_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.generate_key_pushButton.setObjectName("generate_key_pushButton")
        self.horizontalLayout_3.addWidget(self.generate_key_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.crpty_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.crpty_pushButton.setObjectName("crpty_pushButton")
        self.horizontalLayout_3.addWidget(self.crpty_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_key_pushButton.setText(_translate("MainWindow", "加载密钥"))
        self.load_file_pushButton.setText(_translate("MainWindow", "选择文件"))
        self.generate_key_pushButton.setText(_translate("MainWindow", "生成密钥"))
        self.crpty_pushButton.setText(_translate("MainWindow", "加密/解密"))
